version: '3.1'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb